// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBglUjNZTJ0lpzL73jitIDYBmIuJd9PSr8',
    appId: '1:337881050629:android:9d2af7737e9fd59783f66c',
    messagingSenderId: '337881050629',
    projectId: 'chatapp-75ef8',
    databaseURL: 'https://chatapp-75ef8-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-75ef8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfT0-zttO-UDkaLkOi5hkXTmeJ5jNeVgw',
    appId: '1:337881050629:ios:ff24e0db056a175083f66c',
    messagingSenderId: '337881050629',
    projectId: 'chatapp-75ef8',
    databaseURL: 'https://chatapp-75ef8-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-75ef8.firebasestorage.app',
    iosBundleId: 'com.swapdevs.studyswap',
  );
}
